### PR TITLE
amex cards should always have a 4 digit cvc.

### PR DESCRIPTION
**Pull request by stevemckenzie**

### CODE REVIEW

**Comment by jessepollak** [comment]
Thanks for this! Can you make the change in the `.coffee` file then build?

**Comment by stevemckenzie** [comment]
@jessepollak i haven't dealt with submodules in a while. the coffee side is in a different repo.

PR for that here - https://github.com/jessepollak/payment/pull/10

I didn't update this repo to point to that commit. Should I be doing that too?

I'm also not a coffeescript person so can you explain more on what you want me to do on that side?

**Comment by jessepollak** [comment]
Thanks for doing that upstream @stevemckenzie! I'm closing this as I think we're good to go here, then I'll merge in your PR and ship it in the next release (hopefully today).

**Comment by stevemckenzie** [comment]
Thanks @jessepollak :+1:

**Pull request closed without merging**
