### PR TITLE
Fix #280: Reflect pre-filled form values in the card preview

### LINKED ISSUE #280: Pre-filled form input values not reflected in the card preview.
related to #60.

Could you kindly take a look.

If you already fixed it. Could you share some reference code?

### PR DESCRIPTION
**Pull request by tantalum**

### CODE REVIEW

**Comment by melloware** [comment]
There are conflicts with the PR.  Please update your PR or code and submit a new PR please

**Comment by tantalum** [comment]
This PR has been open since 2017. If there is any plan to merge it in I will be happy to resolve the conflicts, but if not I can just delete the PR.

Thank you.

**Comment by melloware** [comment]
Yes if you fix it I can review and merge it.

**Comment by tantalum** [comment]
@melloware The merge conflicts have been resolved.

**Pull request merged**
