### PR TITLE
Allow multiple fields for expiry date

### PR DESCRIPTION
**Pull request by Yottster**
* Removed logic that limits validation to single fields
* Added example with separate month and year field

### CODE REVIEW

**Comment by Yottster** [comment]
dependant on https://github.com/jessepollak/payment/pull/17

**Comment by Yottster** [comment]
hmm.. the built js-files seems to include QJ twice.

**Comment by snc** [comment]
What's the status of this PR?

**Comment by Yottster** [comment]
Im not exactly sure what caused the duplication of QJ in the built files. But I should probably redo this PR. Any idea, @jessepollak ?

**Comment by jessepollak** [comment]
Woo, thank you for this PR (and your corresponding one on payment!). This will go out in v1.2.0!

:+1:

**Pull request merged**
