### PR TITLE
Change .card to .creditcard

### PR DESCRIPTION
**Pull request by DavidReinberger**
The `.card` class was interfering with `.card` at Ratchet UI library. So I have changed it to `.creditcard` which even represents the class better since `card` can be any given card (card like UI).

### CODE REVIEW

**Comment by jessepollak** [comment]
Hmmm, I think I like this change but I'm not sure. I think there's something to be said for having name parity, but I also get that `.card` is pretty non-specific.

Anyone else have thoughts?

If this gets merged, it'll go in the 1.0 release.

**Comment by DavidReinberger** [comment]
.jessecard maybe?

**Comment by jessepollak** [comment]
Mmm, I like that idea better. I think `.jp-card` would be best.

**Comment by jessepollak** [comment]
Ugh, hate to do this, but would you mind opening the same PR off the v-1.0 branch?

**Comment by DavidReinberger** [comment]
sure no prob ;)

**Comment by jessepollak** [comment]
Thank you :)

**Comment by jessepollak** [comment]
Any ETA on this? If it's within the next 30 min, I can wait, otherwise I can just go ahead and do it myself. Sorry to rush — just trying to get this beta out today!

**Comment by jessepollak** [comment]
I did this myself, but merged in your commits — thank you for your hard work!

**Pull request closed without merging**
