### PR TITLE
Add dinersclub brand

### PR DESCRIPTION
**Pull request by caiquecastro**

### CODE REVIEW

**Comment by jessepollak** [comment]
Thank you so much for this PR — really excited to get this merged in!

A few quick things:

1. Can you please add screenshots so we can take a look?
2. Can you remove the `<span>` elements with in the new diner's club `<div>` and replicate them in CSS by using `:before` and `:after`? 

Thank you!

**Comment by caiquecastro** [comment]
dinersclub_card

**Comment by caiquecastro** [comment]
Done @jessepollak

**Comment by BallisticPain** [comment]
@caiquecastro Looking good...

**Comment by caiquecastro** [comment]
Thanks!

**Pull request merged**
