### PR TITLE
Feature/Hipercard

### LINKED ISSUE #378: Hipercard compatibility
Can someone add a Hipercard compatibility? Hipercard is a type of Brazillian credit card.

For more information, see here https://www.npmjs.com/package/creditcard-identifier

### PR DESCRIPTION
**Pull request by luizdesign**
- Add hipercard skin. Fix #378 
screenshot from 2018-10-10 14-26-54

- Add webpack config to compile global as window
- Fix instructions to run development env

### CODE REVIEW

**Comment by yukyolol** [comment]
Hello, it's possible to use input ids instead of creating a form, add inputs and add inputs on that form?
Because a lot of platforms are limited cause of the fact that requires a form to run...

Something like:
```
  	var cardnum = document.getElementById(''inputnumber_id'');
  	var cardexp = document.getElementById(''inputexpiry_id'');
  	var cardcvc = document.getElementById(''inputcvc_id'');
  	var cardname = document.getElementById(''inputname_id'');
          
        formSelectors: {
        	numberInput: cardnum,
        	expiryInput: cardexp,
        	cvcInput: cardcvc,
        	nameInput: cardname
    	}
```

Thanks!

**Comment by murilohns** [comment]
How can I help to merge this PR? @luizdesign @jessepollak

**Comment by luizdesign** [comment]
@murilohns I don't know how you can to help, at this moment the code are done, waiting the maintainers's approve.

**Comment by luizdesign** [comment]
@jessepollak do you can review this PR please?

**Comment by enricodias** [comment]
+ 1 to this.
I'll have to edit the code manually and stop using the cdn since it's been almost 1 year and this PR is still open.

**Comment by luizdesign** [comment]
We are using my fork until this PR to be merged, and @enricodias is have problems to use the card with this skin. @Jason-Cooke Can you help us with this PR?

**Comment by enricodias** [comment]
@luizdesign I'm not having problems with your new skin, it works just fine. I just stated that I'll have to use a custom code since PR's are not getting merged for almost a year. I've also created a PR in jessepollak/payment to add a new prefix to maestro cards which was also not merged.

I was using the JS files on cdnjs, but now I'll have to host a custom code.

**Comment by luizdesign** [comment]
Ok @enricodias, I did not express myself well.

**Comment by melloware** [comment]
This can be closed as it was added in #458

**Pull request closed without merging**
