### PR TITLE
Call setCardType method on initialization. Fix #312

### LINKED ISSUE #312: How do I set the card type upon initialization?
I see how to set most of the values on the card, however the type is not clearly described. Any ideas?

### PR DESCRIPTION
**Pull request by etumyan**
On the library initialization with the filled `placeholders.number` field, card type is not setting up.
So you have to focus on the number input to get it works. This code is fixing the bug, by calling `setCardType` on initialization.

### CODE REVIEW

**Comment by etumyan** [comment]
@jessepollak ping

**Comment by BallisticPain** [comment]
@etumyan 

Sorry for taking so long to get back with you... it appears for now that you have conflicts in your branch with the dist files... Could you attempt to resolve those conflicts so we can test and then hopefully merge? Thanks for your submission!!!

**Comment by etumyan** [comment]
@BallisticPain Here you go.

**Comment by jessepollak** [comment]
Hm, looking at this — it seems like this is a misuse of the `placeholders` option. I would be open to another PR that adds a new configuration value for setting these values on start, but I don't think merging this in as is will work. Sorry — thank you for your hard work on this!

**Pull request closed without merging**
