### PR TITLE
Rollup of fixes

### PR DESCRIPTION
**Pull request by melloware**
This is a rollup of many fixes already presented in other PR's but i needed to build it for the PrimeFaces component I am building.
- [x] Troy card Turkish payment (https://github.com/jessepollak/card/issues/394)
- [x] Hipercard (https://github.com/jessepollak/card/pull/411 https://github.com/jessepollak/card/pull/455)
- [x] UnionPay (https://github.com/jessepollak/card/pull/406)
- [x] Security Vulnerabilities (https://github.com/jessepollak/card/pull/422 https://github.com/jessepollak/card/pull/442)
- [x] Compress CSS and JS for DIST (https://github.com/jessepollak/card/pull/424)
- [x] JCB pattern fixes and many others in Payments module.

### CODE REVIEW

**Comment by jessepollak** [comment]
I'm open to reviewing and merging this and cutting a new release. Can you link all the Issues/PRs that will be resolved and let me know when it's ready for review? I'll then take it from there. Thanks so much for the helpful PR!

**Comment by melloware** [comment]
@jessepollak I put comments above next to each fix from which PR it came from.

As for the Payments module I will submit a PR over there too as it rolls up a bunch of fixes as well.

**Comment by melloware** [comment]
Submitted Payment PR: https://github.com/jessepollak/payment/pull/108

**Comment by melloware** [comment]
PrimeFaces component has been released: https://www.primefaces.org/showcase-ext/sections/creditcard/basicUsage.jsf

**Comment by marcos-alexandre82** [comment]
@jessepollak can you merge these changes into this repository and the payments repository? We are looking forward to an update of your magnificent repository after a few years ;)

**Comment by jessepollak** [comment]
Thanks for doing this - published as v2.5.0. Let me know if you see any issues!

**Comment by marcos-alexandre82** [comment]
@jessepollak Thank you! Now I will investigate why in my code it only shows the skin of Hipercard and Troy, the other cards are just gray. I'll follow the WooCommerce #272 , thanks!

**Pull request merged**
