### PR TITLE
Fix flipped card back transparency issue on Chrome 54

### PR DESCRIPTION
**Pull request by sheck**
### Context

Mac versions of Chrome 54 (53 and lower is unaffected, Windows 54 is unaffected)
### Repro
1. Open example page
2. Focus CVC text box
3. Watch card flip
### Expected

Card flips and only the back is visible
### Actual

Card flips and the back (and parts of the front of the card) are visible

---
### Before

card_js_before
### After

card_js_after

### CODE REVIEW

**Comment by sheck** [comment]
I believe this fixes #279 and #276

**Comment by zeynelakcay** [comment]
thank you sheck

**Comment by codehead** [comment]
Thank you @sheck, it works perfectly.

**Comment by tjratch** [comment]
Thank you!

**Comment by BallisticPain** [comment]
@jessepollak Is this something you're going to merge? It seems you have people interested in submitting fixes for issues... If you don't have time I understand. I also am evaluating your solution, but I prefer one more actively participated. Though I will say there aren't a lot actively participated card solutions out there. Yours looks quite nice... Just trying to give you a direct notification nudge.

Thanks!

**Comment by jessepollak** [comment]
Sorry about the delay on this!

**Comment by jessepollak** [comment]
Published as `2.0.4`!

**Comment by BallisticPain** [comment]
@jessepollak Thanks for your prompt response upon notification. I usually require a notification before I see things as well. ;)

You do seem to have the most actively developed card solution... keep it up. I am looking to replace CardJs with your solution. I would recommend you tout that you can bower install your solution... I can submit a PR for that if you'd like. I like using bower for my dependencies in my PHP project.

Thanks!! Keep up the great work!!

**Comment by jessepollak** [comment]
@BallisticPain it should be published on bower already!

**Pull request merged**
