### PR TITLE
2.5.1 Update with latest Payment JS fixes

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by deivide** [comment]
Can you release this version, please?

**Comment by melloware** [comment]
@jessepollak any chance you could push to NPM?

**Comment by jessepollak** [comment]
@melloware - can you shoot me your NPM username? I can also add you there to do releases. Will cut one now in addition! Thanks!

**Comment by melloware** [comment]
NPM username is "melloware" thanks!

**Pull request merged**
