### PR TITLE
Issue 129

### PR DESCRIPTION
**Pull request by embargiel**
CSS update for American Express and VISA logotypes.

### CODE REVIEW

**Comment by embargiel** [comment]
@jessepollak 

I tried to fix VISA problem and It works correctly right now. (tested on Chrome, Firefox, IE)
I don't have access to MAC, so you have to test on Safari.

Additionaly I updated MasterCard logo, and made some small fixes in AMEX

**Comment by yanc** [comment]
any chance for merging this one? @jessepollak

**Comment by jessepollak** [comment]
I will definitely merge this — excited about the changes :)

@embargiel can you reconcile the merge conflicts? thanks!

**Comment by embargiel** [comment]
Ofc;)
17 sty 2015 03:38 "Jesse Pollak" <notifications@github.com> napisał(a):

**Comment by embargiel** [comment]
@jessepollak bump, I sent you PM

**Comment by jessepollak** [comment]
Can you post images of what the visa and amex logos look like for you? Mine seem off:

I'm seeing:

### American Express

screenshot 2015-01-28 08 43 26

### Visa

screenshot 2015-01-28 08 43 46

And neither of those look particularly right. I've tweaked American Express and gotten it to:

screenshot 2015-01-28 08 44 42

Is that what you're going for? I've merged in your changes and have it building on a branch [here](https://github.com/jessepollak/card/tree/embargiel-issue_129).

**Comment by jessepollak** [comment]
Just wanted to follow up here — any update?

**Comment by victorcastro** [comment]
I want to capture in a variable type of card to send POST in a form.

**Comment by jessepollak** [comment]
This was so close, if you want to help finish it, please reopen and let me know! I'm closing for now.

**Pull request closed without merging**
