### PR TITLE
Style for Elo card

### PR DESCRIPTION
**Pull request by keitoliveira**
Added style for Elo card, reference #200 

screenshot 2015-11-25 20 03 55

Support for this card was developed for Payment too.

### CODE REVIEW

**Comment by jessepollak** [comment]
Oooo, awesome. Checking it out now.

**Comment by jessepollak** [comment]
Thank you! This will go out in v1.2.0!

**Comment by reginaldojunior** [comment]
:+1:

**Comment by wfcreations** [comment]
(y)

**Comment by wfcreations** [comment]
:+1:

**Pull request merged**
