### PR TITLE
Remove focus on output upon input blur

### LINKED ISSUE #163: Card element is not de-focused on input blur
I've spotted this (in the `card.js` file):

```
QJ.on(el, 'blur', function() {
      return QJ.removeClass(el, 'jp-card-focused');
});
```

I believe that the removeClass should be applied to `out` instead

### PR DESCRIPTION
**Pull request by AnnieH**
Fixes #163

### CODE REVIEW

**Comment by jessepollak** [comment]
Thank you so much for the PR, excited to have you contributing! The logic and changes here look terrific!

One issue: it looks like we're having some issues with the browserify build not being deterministic — the `node.extend` changes don't build that way in my setup and I'm not sure why.

Would you mind undoing this commit then recommitting without those changes added? You can do that by doing:

```
$ git reset HEAD~1
$ git add -p # now pick just the logic changes for this fix
$ git commit # add your commit message
$ git push origin master --force
```

Thank you so much for the PR!

**Comment by AnnieH** [comment]
Ok, recommitted. Sorry for the trouble!

**Comment by jessepollak** [comment]
Thank you! No apologies necessary :)

**Comment by jessepollak** [comment]
🎉🎊🎈💫✨

giphy

Way to go on your first open source contribution, I'm certain it's the first of many!

**Comment by AnnieH** [comment]
:+1: 
Thanks for helping me along!

**Comment by jessepollak** [comment]
Anytime :)

**Pull request merged**
